PORT = '/dev/ttyAMA0'
BAUD_RATE = '115200'
READ_TIMEOUT = 0.5
RESPONSE_TIMEOUT = 20
SMSC = '13010314500'  # 上海联通中心号码SMSC 13010314500

# Telephone status
IDLE = 'IDLE'
RING_IN = 'RING_IN'
RING_OUT = 'RING_OUT'
SPEAKING = 'SPEAKING'

RING_IN_EVENT = [RING_IN, IDLE]
RING_OUT_EVENT = [RING_OUT, IDLE]
RING_IN_MISS_EVENT = [IDLE, RING_IN]
RING_OUT_MISS_EVENT = [IDLE, RING_OUT]
RING_IN_SPEAK_EVENT = [SPEAKING, RING_IN]
RING_OUT_SPEAK_EVENT = [SPEAKING, RING_OUT]
RING_IN_HANG_EVENT = [IDLE, SPEAKING, RING_IN]
RING_OUT_HANG_EVENT = [IDLE, SPEAKING, RING_OUT]
